---
resources:
  - name: terraform-test-environment-repo
    type: git
    source:
      uri: https://github.com/EMC-Underground/terraform_test_environment.git
      branch: master


jobs:
  - name: build-test-vm`
    public: true
    plan:
      - get: terraform-test-environment-repo
        trigger: true
      - task: deploy-test-vm
        params:
          VAULT_ADDR: ((vault_addr))
          VAULT_TOKEN: ((root_token))
        config:
          inputs:
            - name: terraform-test-environment-repo
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/terraform
              tag: latest
          run:
            path: sh
            args:
            - -c
            - |
              cd terraform-test-environment-repo
              terraform init
              echo "yes" | terraform apply


