---
resources:
  - name: terraform-test-environment-repo
    type: git
    source:
      uri: https://github.com/EMC-Underground/terraform_test_environment.git
      branch: master


jobs:
  - name: job
    public: true
    plan:
      - get: terraform-test-environment-repo
        trigger: true
      - task: list-files
        params:
          DNS_SUFFIX: ((dnssuffix))
          VAULT_ADDR: ((vault_addr))
          VAULT_TOKEN: ((root_token))
          VSPHERE_PASSWORD: ((vsphere_password))
        config:
          inputs:
            - name: terraform-test-environment-repo
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/terraform
              tag: latest
          run:
            path: sh
            args:
            - -c
            - |
              cd terraform-test-environment-repo
              echo "vsphere_password: ${VSPHERE_PASSWORD}"
              echo "dns suffix: ${DNS_SUFFIX}"
              env
              terraform init
              echo "yes" | terraform apply


