---
resources:
- name: terraform-test-environment-repo
  type: git
  source:
    uri: https://github.com/EMC-Underground/terraform_test_environment.git
    branch: master

jobs:
  - name: update-concourse-pipeline
    public: true
    plan:
      - get: terraform-test-environment-repo
        trigger: true
      - task: update-pipeline
        params:
          CONCOURSE_USERNAME: ((concourse_username))
          CONCOURSE_PASSWORD: ((concourse_password))
          CONCOURSE_URL: ((concourse_url))
          VAULT_ADDR: ((vault_addr))
          VAULT_TOKEN: ((root_token))
        config:
          inputs:
            - name: terraform-test-environment-repo
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: starkandwayne/concourse
              tag: latest
          run:
            path: sh
            args:
            - -c
            - |
              fly -t main login -u ${CONCOURSE_USERNAME} -p ${CONCOURSE_PASSWORD} -c ${CONCOURSE_URL}
              fly -t main sync
              cd ./terraform-test-environment-repo
              fly -t main sp -c ./task/build-test-vm.yml -p build-test-vm -n
              fly -t main unpause-pipeline -p build-test-vm

